modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="stardewmod"
version="0.1"
displayName="Stardew Valley Mod"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="Thanks for this example mod goes to Java"
authors="PenWallet, Ryu and Kanna"
description='''

'''

# Dependencies
[[dependencies.stardewmod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.stardewmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
